server:
    servlet:
        context-path: /api
spring:
    security:
      user:
          password: postgres
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop